### ISSUE TITLE
Base the Kasadaka on Minibian

### ISSUE THREAD

**Issue by cgueret** [WorldWideSemanticWeb/KasaDaka#3]
See https://minibianpi.wordpress.com/
This should simplify the setup process as less cleaning is necessary

**Comment by cgueret** [comment]
Alternatively we could also consider http://www.linuxsystems.it/raspbian-wheezy-armhf-raspberry-pi-minimal-image/

**Comment by abaart** [comment]
I tried this, and in my experience, minibian causes more work than it prevents, because you have to set up a lot more basic things. And with the RPi 2, resources are not a problem anymore.

**Comment by cgueret** [comment]
Ok! Let's close this then.
